#if !canImport(ObjectiveC)
import XCTest

extension BriskMySQLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BriskMySQLTests = [
        ("testConnection", testConnection),
    ]
}

extension FixedWidthIntegerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FixedWidthIntegerTests = [
        ("testFromLittleEndianBytes", testFromLittleEndianBytes),
        ("testToLittleEndianBytes", testToLittleEndianBytes),
    ]
}

extension MySQLPacketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MySQLPacketTests = [
        ("testByteBufferConversions", testByteBufferConversions),
    ]
}

extension MySQLStandardPacketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MySQLStandardPacketTests = [
        ("testBytes", testBytes),
        ("testIntegers", testIntegers),
        ("testStrings", testStrings),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BriskMySQLTests.__allTests__BriskMySQLTests),
        testCase(FixedWidthIntegerTests.__allTests__FixedWidthIntegerTests),
        testCase(MySQLPacketTests.__allTests__MySQLPacketTests),
        testCase(MySQLStandardPacketTests.__allTests__MySQLStandardPacketTests),
    ]
}
#endif
