#if !canImport(ObjectiveC)
import XCTest

extension FixedWidthIntegerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FixedWidthIntegerTests = [
        ("testFromLittleEndianBytes", testFromLittleEndianBytes),
        ("testToLittleEndianBytes", testToLittleEndianBytes),
    ]
}

extension MySQLPacketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MySQLPacketTests = [
        ("testByteBufferConversions", testByteBufferConversions),
        ("testInvalidByteBufferConversions", testInvalidByteBufferConversions),
        ("testPacketLength", testPacketLength),
        ("testSequenceNumber", testSequenceNumber),
    ]
}

extension MySQLStandardPacketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MySQLStandardPacketTests = [
        ("testCString", testCString),
        ("testEndOfFileLengthBytes", testEndOfFileLengthBytes),
        ("testFixedLengthBytes", testFixedLengthBytes),
        ("testFixedLengthString", testFixedLengthString),
        ("testFixedWidthInteger", testFixedWidthInteger),
        ("testInvalidInputs", testInvalidInputs),
        ("testLengthEncodedBytes", testLengthEncodedBytes),
        ("testLengthEncodedInteger", testLengthEncodedInteger),
        ("testLengthEncodedStrings", testLengthEncodedStrings),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FixedWidthIntegerTests.__allTests__FixedWidthIntegerTests),
        testCase(MySQLPacketTests.__allTests__MySQLPacketTests),
        testCase(MySQLStandardPacketTests.__allTests__MySQLStandardPacketTests),
    ]
}
#endif
